---
- name: Install HTTP server
  hosts: g2
  become: yes

  tasks:
  - name: Install HHTPD
    yum:
      name: httpd
      state: present
    when : ansible_distribution == "CentOS"

  - name: start httpd
    service:
      name: httpd
      state: started
    when : ansible_distribution == "CentOS"

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes
    when : ansible_distribution == "CentOS"

  - name: Install Apache2
    apt:
      name: apache2
      state: present
    when : ansible_distribution == "Debian"

  - name: start apache2
    service:
      name: apache2
      state: started
    when : ansible_distribution == "Debian"

  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes
    when : ansible_distribution == "Debian"
...
